openapi: 3.0.0
info:
  title: Authors API
  version: 1.0.0
  description: API endpoints for managing authors.
servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /:
    get:
      summary: List Authors
      description: Retrieves a list of all authors.
      tags:
        - Authors
      responses:
        '200':
          description: A list of authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'

    post:
      summary: Create Author
      description: Creates a new author with name and email.
      tags:
        - Authors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthorDTO'
      responses:
        '201':
          description: Author created successfully
        '400':
          description: Invalid input data

  /{id}:
    get:
      summary: Get Specific Author
      description: Retrieves details of a specific author by their ID.
      tags:
        - Authors
      parameters:
        - name: id
          in: path
          required: true
          description: Unique ID of the author
          schema:
            type: string
      responses:
        '200':
          description: Details of the specified author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: Author not found

    put:
      summary: Update Author
      description: Updates an existing author's details.
      tags:
        - Authors
      parameters:
        - name: id
          in: path
          required: true
          description: Unique ID of the author
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthorDTO'
      responses:
        '200':
          description: Author updated successfully
        '400':
          description: Invalid input data
        '404':
          description: Author not found

    delete:
      summary: Delete Author
      description: Deletes a specific author.
      tags:
        - Authors
      parameters:
        - name: id
          in: path
          required: true
          description: Unique ID of the author
          schema:
            type: string
      responses:
        '200':
          description: Author deleted successfully
        '404':
          description: Author not found

components:
  schemas:
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier of the author
        name:
          type: string
          description: Name of the author
        email:
          type: string
          format: email
          description: Email of the author

    CreateAuthorDTO:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 20
          description: Name of the author
        email:
          type: string
          format: email
          description: Email of the author

    UpdateAuthorDTO:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 20
          description: Name of the author
        email:
          type: string
          format: email
          description: Email of the author
