openapi: 3.0.0
info:
  title: Posts API
  version: 1.0.0
  description: API endpoints for managing posts.
servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /posts:
    get:
      summary: List Posts
      description: Retrieves a list of all posts.
      tags:
        - Posts
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

    post:
      summary: Create Post
      description: Creates a new post.
      tags:
        - Posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: Post created successfully
        '400':
          description: Invalid input data

  /posts/{id}:
    get:
      summary: Get Specific Post
      description: Retrieves details of a specific post by its ID.
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          description: Unique ID of the post
          schema:
            type: string
      responses:
        '200':
          description: Details of the specified post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found

    put:
      summary: Update Post
      description: Updates an existing post's details.
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          description: Unique ID of the post
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Post updated successfully
        '400':
          description: Invalid input data
        '404':
          description: Post not found

    delete:
      summary: Delete Post
      description: Deletes a specific post.
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          description: Unique ID of the post
          schema:
            type: string
      responses:
        '200':
          description: Post deleted successfully
        '404':
          description: Post not found

components:
  schemas:
    Post:
      type: object
      required:
        - title
        - content
        - authorId
      properties:
        title:
          type: string
          description: Title of the post
        content:
          type: string
          description: Content of the post
        authorId:
          type: integer
          format: int64
          description: ID of the author who created the post
