version: '3'

networks:
  backend:

services:
  postgres:
    image: postgres:latest
    env_file: ./.env
    restart: on-failure
    container_name: postgres
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6.14
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - backend

  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
#      - NODE_ENV=development
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: yarn dev
    ports:
      - "3000:3000"
    networks:
      - backend

volumes:
  postgres:
